control_loop_node:
  robot_hardware:
    - dynamixel_control
  loop_frequency: 100
  cycle_time_error_threshold: 0.1
  dynamixel_control:
    type: dynamixel/hardware_interface_p1
    serial_interface: /dev/ttyUSB0
    baudrate: 1000000 # in bauds
    read_timeout: 0.05 # in seconds
    scan_timeout: 0.05 # in seconds
    # Cofniguration of the servos
    servos:
      arm_joint_1:
        # hardware ID of the actuator
        id: 1
        # offset to be added, in radians, to the position of an actuator
        offset: 3.141 # in rad
        command_interface: velocity
      arm_joint_2:
        id: 2
        offset: 3.141
    # default mode
    default_command_interface: position

dynamixel_controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  pos_controller:
    type: position_controllers/JointPositionController
    joint: arm_joint_2

  vel_controller:
    type: velocity_controllers/JointVelocityController
    joint: arm_joint_1
  

